### ISSUE TITLE
Depending on "ready" callback, runs only once

### ISSUE THREAD

**Issue by bensmeets** [kadirahq/subs-manager#29]
Not sure if I'm doing something that should be done different, but it seems the "onReady" callback is only called once. If you sucscribe to the same pub again, everything is cached and the onReady is skipped. This makes it tricky to hook logic into there. E.g., I use the onReady to set a var, that will make the helper trigger DOM updates only once. Therefore, the second time, it renders nothing.

Or is there another way I should do this in SubMgr? :)

**Comment by zimt28** [comment]
@arunoda?

**Comment by satyavh** [comment]
+1 

I run into exactly the same issue. Whenever I subscribe to the cached subscription, the onReady callback doesn't trigger again.

**Comment by center777** [comment]
+1

**Comment by pao807** [comment]
+1
