### ISSUE TITLE
Sometimes data lost

### ISSUE THREAD

**Issue by bensmeets** [kadirahq/subs-manager#30]
Just a heads up, in case it is good to know.

I came across the issue, that some data will be lost in the client when I create a new subscription. E.g., I have a user with an avatar property. When I create a new subscription in an autorun, which is totally unrelated to these avatars (at first sight), the avatar collection is cleared. This doesn't happen if I replace SubMgr with default subscriptions.

**Comment by arunoda** [comment]
Okay. Seems like a big issue.
Is it possible to have a sample code as a gist or as a repo.
So, I can locally replicate and fix this quickly.

**Comment by bensmeets** [comment]
Will try to get something like my setup in meteorpad. Might take same time because of the setup I use though :(

**Comment by arunoda** [comment]
Okay. That's perfect.
I'll wait for that.
I couldn't try to replicate it locally.

**Comment by bensmeets** [comment]
After trying a couple of hours to get something reproducable to you, I'm stuck while banging my head against the wall. There is never 1 single reproducable way when it goes wrong. Not even a way for sure to know what the cause is. It feels totally random. Since I can't share the entire project, it's hard to prepare something that is and still contains the issue.

I've been debugging like crazy (which is hell in Meteor's publish/subscribe if you don't know where to look btw :) ) and the more I try things, the more I feel like it's not so much a subs-manager problem. It feels more like something within a published Meteor.users collection is deciding that some added meta fields to the user collection need to be removed (I see the Avatar's image being removed at random in the ddp analyzer).

So let's assume it's my misunderstanding of publications, or maybe something regarding the reactive joins I'm publishing or whatnot. I'm gonna keep on trying to find the issue, if it is anything related to subs manager, will get back to you.

Thanks for the quick reply :)

**Comment by arunoda** [comment]
Great. If you found something let me know.
I will help you to fix it.

**Comment by jimmiebtlr** [comment]
If it's in a autorun function, do the parameters that it is subscribed to change?  If so, it may be reaching the maximum number of cached subscriptions and unsubscribing from the avatar's subscription.

**Comment by VioletaCalvo** [comment]
Hi!

Same issue here. Have you found the problem?
I'll try to reproduce it.
When I make a new subscription with `subs.subscribe` to get more documents for a subscription (infinite scroll; *ex: user activity*), other subscriptions are cleared but I still need them (*ex: user info*). If I use `Meteor.subscribe` inside `this.autorun` this doesn't happen.

**Comment by arunoda** [comment]
@VioletaCalvo this may be reason of the default cache limits. Try to increase it.
See: https://github.com/kadirahq/subs-manager#cache-control

**Comment by VioletaCalvo** [comment]
Thank you @arunoda I'll try that :blush:

**Comment by miri-am** [comment]
also happening here. Did anybody identify the underlying cause? @VioletaCalvo did increasing the cacheLimit help?

**Comment by miri-am** [comment]
I would expect that `subs.subscribe` inside an autorun is reran in case it is expired. Is that maybe not the case?

**Comment by VioletaCalvo** [comment]
Sorry for the late reply @miri-am. 
I couldn't fix the problem with `cacheLimit` so I used `Meteor.subscribe`
