### ISSUE TITLE
Any way to interrogate the subs manager to see the current subscriptions

### ISSUE THREAD

**Issue by wesyah234** [kadirahq/subs-manager#35]
I looked at the code and I don't think you implemented this, so maybe it's more of a feature request, unless I'm overlooking something and there's a better way...

so, I have :
var searchSubsManager = new SubsManager({
    // keep the last 3 searches run
    cacheLimit: 3,
    expireIn: 5
});

and every time the user runs a search query to the database, I do:

    searchSubsManager.subscribe("search", query);

which runs the query on the server, then I do a find to retrieve the results.

We're keeping track of the last 3 search queries run, and this is working great, but I would like to be able to show the user on the screen what those last 3 search queries were.  Is there a way to ask the searchSubsManager object to give me the cached subscriptions along with the parameter passed to each?.. I can see it in the Subs Manager as _cacheList, but not sure where to go from there.  I can also see them in mongol (meteor toys)

**Comment by lorensr** [comment]
Re: `searchSubsManager._cacheList`, in the below example, each object has an `args` array. `args[0]` is the publication name and `args[1]` is the parameter.

![image](https://cloud.githubusercontent.com/assets/251288/8106372/ab63b18a-100e-11e5-8a18-cc9407611c8a.png)

**Comment by wesyah234** [comment]
Thanks... that helps!

**Comment by chmac** [comment]
@wesyah234 Please close the issue if you feel like your question has been answered. :+1:
