### ISSUE TITLE
infinite loop after 10 subscribe (cacheLimit)

### ISSUE THREAD

**Issue by darkship** [kadirahq/subs-manager#45]
In my repo you will be able to subscribe through iron-router's waitOn using subs-manager. 

From 1 to 10 subscribe, everything is fine.
After 10, there is an infinite loop.

https://github.com/darkship/test_SubsManager

<code>cacheLimit</code> is 10 by default. If you increase it you can put more but after the limit you have an infinite loop again. Shouldn't we have a warn message and prevent to add more subscriptions ?

**Comment by rijk** [comment]
Helped me with debugging a similar problem. Thanks!
