### ISSUE TITLE
when, where to use "reset or clear"?

### ISSUE THREAD

**Issue by thearabbit** [kadirahq/subs-manager#51]
I am a new for this package.
But don't understand `when, where to use "reset or clear"?`
```js
// In docs
var subs = new SubsManager(); // use in router such as `Flow Router`

// later in some other place
subs.clear()/.reset(); // Where and When??? 
```
I think that we can't us `subs` in `global`, because it declare with `var`.
Please help me.

**Comment by talha-asad** [comment]
just remove the ```var``` ...

**Comment by thearabbit** [comment]
Thanks for your reply.

**Comment by pdiniz13** [comment]
Neither one is working for fine
