### ISSUE TITLE
FlowRouter?

### ISSUE THREAD

**Issue by derwaldgeist** [kadirahq/subs-manager#62]
The docs only refer to IronRouter. Does this package also work with FlowRouter? I assume that, since both packages are from the same developer. But I'm not really sure. So it would be helpful if the docs mentioned FR as well (or state that it does not work).

**Comment by arunoda** [comment]
Check this: https://kadira.io/academy/meteor-routing-guide/content/subscriptions-and-data-management/using-subs-manager

**Comment by derwaldgeist** [comment]
Thanks!
