### ISSUE TITLE
Update docs with FlowRouter

### ISSUE THREAD

**Issue by avalanche1** [kadirahq/subs-manager#63]
Since IR is obsolete and you demoted wait-on and router-level subscriptions, docs should be updated accordingly.

**Comment by talha-asad** [comment]
+1

**Comment by avalanche1** [comment]
Thanks!

**Comment by arunoda** [comment]
@talha-asad this is **not** an unmaintained project.
In the FlowRouter Guide, there is a complete section about SubsManager.
See: https://kadira.io/academy/meteor-routing-guide/content/subscriptions-and-data-management/using-subs-manager

**Comment by arunoda** [comment]
FYI: Update the docs.

**Comment by avalanche1** [comment]
:+1:

**Comment by talha-asad** [comment]
@arunoda The docs should be on the ReadMe. Maybe thats where the problem is. Kadira, Meteorhacks, Eventedmind, ReadMe, Wiki. So confusing, different versions of the same thing.

**Comment by arunoda** [comment]
You got it wrong. When using FlowRouter, it's recommended to follow our
guide. Is has the necessary docs for subs-manager.

Anyway, I should have update docs here before. Thanks for adding this
issue.

BTW: You should try to respect to people who build these projects. This is
open source and it's a culture. We respect each other and argue.

If There is no EventedMind, other people and us you won't be able to build
a meteor app easily.
