### ISSUE TITLE
Issue when losing connection with server

### ISSUE THREAD

**Issue by pdiniz13** [kadirahq/subs-manager#68]
During a hot code push the client is not refreshing and the server keeps continuously republishing the data to the client. Once you manually refresh the page the server and the client get back in sync and the constant publications stop. This only happens on a hot code push, if you stop the app and restart it manually the page refreshes and this is not an issue.

**Comment by pdiniz13** [comment]
This was being caused by the expiration tag of the subscription being set to, too large a value. The docs should reflect that if the expiration tag is set to, too far in the future that the subs will not be reset in case of a server reload.

**Comment by arunoda** [comment]
This seems like a bug to me. Can you send me a sample repo with steps to reproduce this.

**Comment by pdiniz13** [comment]
This ended up being a issue with groundDB and not the subs-manager package. So i'll just go ahead and close the issue.
