### ISSUE TITLE
Uncaught TypeError: this._addSub is not a function

### ISSUE THREAD

**Issue by SachaG** [kadirahq/subs-manager#75]
Trying to use Subs Manager in Nova on 1.3, getting this error. I'm not sure if it's coming from something I'm doing? Does anybody else have that problem?

**Comment by arthuryeti** [comment]
Any news?

**Comment by SachaG** [comment]
Turns out it was a problem on my end. I wanted to make it possible to either use SubsManager.subscribe or the regular Meteor.subscribe so I was doing this:

```
const Subs = new SubsManager();
const subscribeFunction = useSubsManager ? Subs.subscribe : Meteor.subscribe;
const subscription = subscribeFunction(this.props.publication, terms);
```

Which meant that `this` inside `Subs.subscribe` wasn't being properly bound. The solution:

```
const Subs = new SubsManager();
const subscribeFunction = useSubsManager ? Subs.subscribe.bind(Subs) : Meteor.subscribe;
const subscription = subscribeFunction(this.props.publication, terms);
```
