### ISSUE TITLE
when the user logout the app, he still able to find collections on console

### ISSUE THREAD

**Issue by humbertocruz** [kadirahq/subs-manager#78]
Hello,

I notice that the user still ablle to search collections using the console browser. For example: s = new SubsManager(); sub = s.subscribe('allUsers');  u = Meteor.users.find();
I tried put a condition on the publish ( if (!this.userId) return false ) but with that the user can't login.

what are the best way to avoid unauthorized users subscribe the data before login the app ?

thanks

**Comment by Bandit** [comment]
Call `clear()` after logout?

**Comment by humbertocruz** [comment]
great idea, thanks
